language: python
python:
  - "2.7"
  - "3.3"
install:
  - sudo apt-get install -y graphviz
  - pip install coveralls pytest-cov
script: py.test --cov=dotter --cov-report=term-missing
after_success:
  - coveralls
